[package]
name = "plugin-argon2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
argon2 = "0.5"
chacha20poly1305 = "0.10"
extism-pdk = "1.2"
serde = { version = "1.0", features = ["derive"] }
